<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TicketFlow.Contracts\TicketFlow.Contracts.csproj" />
    <ProjectReference Include="..\TicketFlow.Domain\TicketFlow.Domain.csproj" />
  </ItemGroup>

</Project>
